## Matching Indicitor of Compromise and Indicitor of Attack

available information: 
    1. 20.93.23.234 --- attack IP
    2. malicious code is written in Python
    3. malicious package is colorsapi-6.6.7, the trigger is setup.py

In [3]:
# check timestamp and known information
import pandas as pd
from pathlib import Path

In [12]:
event_data_path = Path.cwd().parent.parent.parent.joinpath("data", "scenario1", "windows", "query_data_event.csv")
conn_data_path = Path.cwd().parent.parent.parent.joinpath("data", "scenario1", "windows", "query_data_conn.csv")
security_data_path = Path.cwd().parent.parent.parent.joinpath("data", "scenario1", "windows", "query_data_security.csv")

In [13]:
eventdf = pd.read_csv(event_data_path)
conndf = pd.read_csv(conn_data_path)
secdf = pd.read_csv(security_data_path)

In [8]:
eventdf.columns

Index(['TenantId', 'SourceSystem', 'TimeGenerated [UTC]', 'Source', 'EventLog',
       'Computer', 'EventLevel', 'EventLevelName', 'ParameterXml', 'EventData',
       'EventID', 'RenderedDescription', 'AzureDeploymentID', 'Role',
       'EventCategory', 'UserName', 'Message', 'MG', 'ManagementGroupName',
       'Type', '_ResourceId'],
      dtype='object')

In [9]:
eventdf = eventdf.sort_values(by="TimeGenerated [UTC]", ascending=True)

In [21]:
eventdf

,TenantId,SourceSystem,TimeGenerated [UTC],Source,EventLog,Computer,EventLevel,EventLevelName,ParameterXml,EventData,...,RenderedDescription,AzureDeploymentID,Role,EventCategory,UserName,Message,MG,ManagementGroupName,Type,_ResourceId
0,8f3c4b92-3deb-4244-a26b-bf9f3a4ca94f,OpsManager,"22/04/2025, 14:42:38.858",NPMD Agent,Operations Manager,Office-Wins,4,Information,<Param>U04/22/25 14:42:38:853 T1dc I NPM:...,"<DataItem type=""System.XmlData"" time=""2025-04-...",...,U04/22/25 14:42:38:853 T1dc I NPM::Enviro...,NaN,NaN,0,NaN,NaN,00000000-0000-0000-0000-000000000001,AOI-8f3c4b92-3deb-4244-a26b-bf9f3a4ca94f,Event,/subscriptions/125ecc14-76ae-4cae-918e-d8da5f3...
1,8f3c4b92-3deb-4244-a26b-bf9f3a4ca94f,OpsManager,"22/04/2025, 14:42:38.858",NPMD Agent,Operations Manager,Office-Wins,4,Information,<Param>U04/22/25 14:42:38:858 T1dc I NPM:...,"<DataItem type=""System.XmlData"" time=""2025-04-...",...,U04/22/25 14:42:38:858 T1dc I NPM::Enviro...,NaN,NaN,0,NaN,NaN,00000000-0000-0000-0000-000000000001,AOI-8f3c4b92-3deb-4244-a26b-bf9f3a4ca94f,Event,/subscriptions/125ecc14-76ae-4cae-918e-d8da5f3...
2,8f3c4b92-3deb-4244-a26b-bf9f3a4ca94f,OpsManager,"22/04/2025, 14:42:38.858",NPMD Agent,Operations Manager,Office-Wins,4,Information,<Param>U04/22/25 14:42:38:858 T1dc I NPM:...,"<DataItem type=""System.XmlData"" time=""2025-04-...",...,U04/22/25 14:42:38:858 T1dc I NPM::Enviro...,NaN,NaN,0,NaN,NaN,00000000-0000-0000-0000-000000000001,AOI-8f3c4b92-3deb-4244-a26b-bf9f3a4ca94f,Event,/subscriptions/125ecc14-76ae-4cae-918e-d8da5f3...
3,8f3c4b92-3deb-4244-a26b-bf9f3a4ca94f,OpsManager,"22/04/2025, 14:42:38.858",NPMD Agent,Operations Manager,Office-Wins,4,Information,<Param>U04/22/25 14:42:38:858 T1dc I NPM:...,"<DataItem type=""System.XmlData"" time=""2025-04-...",...,U04/22/25 14:42:38:858 T1dc I NPM::Enviro...,NaN,NaN,0,NaN,NaN,00000000-0000-0000-0000-000000000001,AOI-8f3c4b92-3deb-4244-a26b-bf9f3a4ca94f,Event,/subscriptions/125ecc14-76ae-4cae-918e-d8da5f3...
4,8f3c4b92-3deb-4244-a26b-bf9f3a4ca94f,OpsManager,"22/04/2025, 14:42:38.863",NPMD Agent,Operations Manager,Office-Wins,4,Information,<Param>U04/22/25 14:42:38:863 T1dc I NPM:...,"<DataItem type=""System.XmlData"" time=""2025-04-...",...,U04/22/25 14:42:38:863 T1dc I NPM::Enviro...,NaN,NaN,0,NaN,NaN,00000000-0000-0000-0000-000000000001,AOI-8f3c4b92-3deb-4244-a26b-bf9f3a4ca94f,Event,/subscriptions/125ecc14-76ae-4cae-918e-d8da5f3...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,62f68ee4-9639-4a69-b820-5881cfe41a62,OpsManager,"22/04/2025, 14:27:25.351",Microsoft-Windows-Sysmon,Microsoft-Windows-Sysmon/Operational,Office-Wins,4,Information,<Param>Usermode</Param><Param>2025-04-22 14:27...,"<DataItem Type=""System.XmlData"" time=""2025-04-...",...,Network connection detected: RuleName: Usermod...,NaN,NaN,3,S-1-5-18,NaN,00000000-0000-0000-0000-000000000001,AOI-62f68ee4-9639-4a69-b820-5881cfe41a62,Event,/subscriptions/125ecc14-76ae-4cae-918e-d8da5f3...
996,62f68ee4-9639-4a69-b820-5881cfe41a62,OpsManager,"22/04/2025, 14:27:25.431",Microsoft-Windows-Sysmon,Microsoft-Windows-Sysmon/Operational,Office-Wins,4,Information,<Param>-</Param><Param>2025-04-22 14:27:23.362...,"<DataItem Type=""System.XmlData"" time=""2025-04-...",...,Dns query: RuleName: - UtcTime: 2025-04-22 14:...,NaN,NaN,22,S-1-5-18,NaN,00000000-0000-0000-0000-000000000001,AOI-62f68ee4-9639-4a69-b820-5881cfe41a62,Event,/subscriptions/125ecc14-76ae-4cae-918e-d8da5f3...
997,62f68ee4-9639-4a69-b820-5881cfe41a62,OpsManager,"22/04/2025, 14:27:26.391",Microsoft-Windows-Sysmon,Microsoft-Windows-Sysmon/Operational,Office-Wins,4,Information,<Param>Usermode</Param><Param>2025-04-22 14:27...,"<DataItem Type=""System.XmlData"" time=""2025-04-...",...,Network connection detected: RuleName: Usermod...,NaN,NaN,3,S-1-5-18,NaN,00000000-0000-0000-0000-000000000001,AOI-62f68ee4-9639-4a69-b820-5881cfe41a62,Event,/subscriptions/125ecc14-76ae-4cae-918e-d8da5f3...
998,62f68ee4-9639-4a69-b820-5881cfe41a62,OpsManager,"22/04/2025, 14:27:27.431",Microsoft-Windows-Sysmon,Microsoft-Windows-Sysmon/Operational,Office-Wins,4,Information,<Param>Usermode</Param><Param>2025-04-22 14:27...,"<DataItem Type=""System.XmlData"" time=""2025-04-...",...,Network connection detected: RuleName: Usermod...,NaN,NaN,3,S-1-5-18,NaN,00000000-0000-0000-0000-000000000001,AOI-62f68ee4-9639-4a69-b820-5881cfe41a62,Event,/subscriptions/125ecc14-76ae-4cae-918e-d8da5f3...
999,62f68ee4-9639-4a69-b820-5881cfe41a62,OpsManager,"22/04/2025, 14:27:29.499",Microsoft-Windows-Sysmon,Microsoft-Windows-Sysmon/Operational,Office-Wins,4,Information,<Param>Usermode</Param><Param>2025-04-22 14:27...,"<DataItem Type=""System.XmlData"" time=""2025-04-...",...,Network connection detected: RuleName: Usermod...,NaN,NaN,3,S-1-5-18,NaN,00000000-0000-0000-0000-000000000001,AOI-62f68ee4-9639-4a69-b820-5881cfe41a62,Event,/subscriptions/125ecc14-76ae-4cae-918e-d8da5f3...

In [23]:
# find IOCs and IOAs from Sysmon based events

eventdf[eventdf['Source'] == "Microsoft-Windows-Sysmon"][['ParameterXml', 'EventData', 'RenderedDescription', 'AzureDeploymentID', 'Role',
       'EventCategory', 'UserName', 'Message',]]

,ParameterXml,EventData,RenderedDescription,AzureDeploymentID,Role,EventCategory,UserName,Message
237,<Param>Usermode</Param><Param>2025-04-22 14:16...,"<DataItem Type=""System.XmlData"" time=""2025-04-...",Network connection detected: RuleName: Usermod...,NaN,NaN,3,S-1-5-18,NaN
238,<Param>Usermode</Param><Param>2025-04-22 14:17...,"<DataItem Type=""System.XmlData"" time=""2025-04-...",Network connection detected: RuleName: Usermod...,NaN,NaN,3,S-1-5-18,NaN
239,<Param>-</Param><Param>2025-04-22 14:17:03.504...,"<DataItem Type=""System.XmlData"" time=""2025-04-...",Process terminated: RuleName: - UtcTime: 2025-...,NaN,NaN,5,S-1-5-18,NaN
240,<Param>Usermode</Param><Param>2025-04-22 14:17...,"<DataItem Type=""System.XmlData"" time=""2025-04-...",Network connection detected: RuleName: Usermod...,NaN,NaN,3,S-1-5-18,NaN
241,<Param>-</Param><Param>2025-04-22 14:17:04.530...,"<DataItem Type=""System.XmlData"" time=""2025-04-...",Process Create: RuleName: - UtcTime: 2025-04-2...,NaN,NaN,1,S-1-5-18,NaN
...,...,...,...,...,...,...,...,...
995,<Param>Usermode</Param><Param>2025-04-22 14:27...,"<DataItem Type=""System.XmlData"" time=""2025-04-...",Network connection detected: RuleName: Usermod...,NaN,NaN,3,S-1-5-18,NaN
996,<Param>-</Param><Param>2025-04-22 14:27:23.362...,"<DataItem Type=""System.XmlData"" time=""2025-04-...",Dns query: RuleName: - UtcTime: 2025-04-22 14:...,NaN,NaN,22,S-1-5-18,NaN
997,<Param>Usermode</Param><Param>2025-04-22 14:27...,"<DataItem Type=""System.XmlData"" time=""2025-04-...",Network connection detected: RuleName: Usermod...,NaN,NaN,3,S-1-5-18,NaN
998,<Param>Usermode</Param><Param>2025-04-22 14:27...,"<DataItem Type=""System.XmlData"" time=""2025-04-...",Network connection detected: RuleName: Usermod...,NaN,NaN,3,S-1-5-18,NaN
999,<Param>Usermode</Param><Param>2025-04-22 14:27...,"<DataItem Type=""System.XmlData"" time=""2025-04-...",Network connection detected: RuleName: Usermod...,NaN,NaN,3,S-1-5-18,NaN